name: Tyrasoft Attendance CI

on:
  push: 
    tags: 
     - release-**
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          architecture: x64
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: pwd
      - run: chmod 777 ./*
      - run: echo ${{ secrets.UPLOAD_KEY }} | base64 --decode > android/app/upload-keystore.jks
      - run: echo "storeFile=upload-keystore.jks" >> android/key.properties
      - run: echo "keyAlias=${{secrets.KEYSTORE_KEY_ALIAS}}" >> android/key.properties
      - run: echo "storePassword=${{secrets.KEYSTORE_STORE_PASSWORD}}" >> android/key.properties
      - run: echo "keyPassword=${{secrets.KEYSTORE_KEY_PASSWORD}}" >> android/key.properties
      - run: flutter build apk --release
      - run: cp build/app/outputs/flutter-apk/app-release.apk app.apk
      
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.apk

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: app

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g firebase-tools
      - name: Upload to App Distribution
        run: firebase appdistribution:distribute app.apk --app "${{secrets.FIREBASE_APP_ID}}" --release-notes "${{ github.event.head_commit.message }}" --groups "me,tyrasoft" --token "${{secrets.FIREBASE_CI_TOKEN}}"
